feat: send-payload new action --url (#6)
Co-authored-by: pyxide <pyxide@pyxide.org>

diff --git a/testdata/send-payload b/testdata/send-payload
--- a/testdata/send-payload
+++ b/testdata/send-payload
@@ -5,6 +5,7 @@ usage() {
    Sends a payload to Josuke server.
 Usage:
  send-payload <JSON server conf> <hook name> <payload file>
+ send-payload <JSON server conf> --url : prints the server base URL
  send-payload --help : prints this help.
 EOF
 }
@@ -14,27 +15,7 @@ if test 0 = $# || test '--help' = "$1"; then usage; exit 0; fi
 jqExe='jq'
 #jqExe='/p/dev/app/jq/jq-1.6-win32.exe'
 dbg='false'
-dbg='true'
-
-#thisDir=$(dirname "$0")
-
-serverConf="$1"
-hookName="$2"
-payloadFile="$3"
-
-if test -z "$serverConf"; then printf 'send-payload: missing configuration\n'>&2; exit 1; fi
-if test -z "$hookName"; then printf 'send-payload: missing hook name\n'>&2; exit 1; fi
-if test -z "$payloadFile"; then printf 'send-payload: missing payload\n'>&2; exit 1; fi
-
-if test ! -f "$serverConf"; then
-	printf 'send-payload: configuration not found: %s\n' "$serverConf">&2
-	exit 1
-fi
-if test ! -f "$payloadFile"; then
-	printf 'send-payload: payload not found: %s\n' "$payloadFile">&2
-	exit 1
-fi
-
+#dbg='true'
 
 # read values from the server configuration
 getServerUrlFromConf() {
@@ -50,6 +31,28 @@ getServerUrlFromConf() {
 	fi
 	printf '%s' "$protocol://$host:$port"
 }
+
+serverConf="$1"
+hookName="$2"
+payloadFile="$3"
+
+if test -z "$serverConf"; then printf 'send-payload: missing configuration\n'>&2; exit 1; fi
+if test '--url' = "$hookName"; then
+	getServerUrlFromConf "$serverConf"
+	exit 0
+fi
+
+if test -z "$hookName"; then printf 'send-payload: missing hook name\n'>&2; exit 1; fi
+if test -z "$payloadFile"; then printf 'send-payload: missing payload\n'>&2; exit 1; fi
+
+if test ! -f "$serverConf"; then
+	printf 'send-payload: configuration not found: %s\n' "$serverConf">&2
+	exit 1
+fi
+if test ! -f "$payloadFile"; then
+	printf 'send-payload: payload not found: %s\n' "$payloadFile">&2
+	exit 1
+fi
 
 # - JSON file
 # - hook name
